name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: Tests (Py${{ matrix.python }} · ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[full] --prefer-binary
          pip install coverage pytest-cov
      - name: Run tests with coverage
        run: |
          pytest -q --cov=a3d --cov-report=xml --cov-report=term-missing
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-py${{ matrix.python }}
          path: |
            coverage.xml
      - name: Upload out/ artifacts (plots/csv)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: research-outputs-${{ matrix.os }}-py${{ matrix.python }}
          path: |
            out/
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
