name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: Tests (Py${{ matrix.python }} · ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[full] --prefer-binary
      - run: pytest -q
