name: Release (TestPyPI)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build sdist and wheel
        run: python -m build
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*